export type VarKey =
  | "CHUANSHENYUN_API_BASE"
  | "DEEPSEEK_API_BASE"
  | "IMAGEGEN_API_BASE"
  | "ALIYUN_OSS_BUCKET"
  | "ALIYUN_OSS_REGION"
  | "APP_ENV"
  | "ADMIN_BOOTSTRAP_EMAIL";

export type SecretKey =
  | "USER_CREDENTIAL_MASTER_KEY"
  | "INVITE_CODE_HMAC_KEY"
  | "RENDER_WORKER_TOKEN"
  | "ALIYUN_OSS_ACCESS_KEY_ID"
  | "ALIYUN_OSS_ACCESS_KEY_SECRET";
